// stencil/src/components/login-component/login-component.tsx
import { Component, Prop, State } from '@stencil/core';
import { RouterHistory } from '@stencil/router';

@Component({
  tag: 'login-component',
  shadow: false
})
export class LoginComponent {

  @State() username: string;
  @State() password: string;
  @Prop() history: RouterHistory;

  render() {
    return (
      <div>
        <div class="form-group col-sm-4">
          <label>Username</label>
          <input type="text" class="form-control"
            value={this.username}
            onInput={(event: any) => this.username = event.target.value}
            placeholder="Username" />
        </div>
        <div class="form-group col-sm-4">
          <label>Password</label>
          <input type="password" class="form-control"
            value={this.password}
            onInput={(event: any) => this.password = event.target.value}
            placeholder="Password" />
        </div>
        <div class="form-group col-sm-4">
          <button type="button" class="btn btn-primary" onClick={() => this.handleClick()} >
            Login
          </button>
        </div>
      </div>
    );
  }

  handleClick() {
    fetch('http://localhost:4000/authenticate', {
      body: JSON.stringify({ username: this.username, password: this.password }),
      method: 'POST',
      headers: {
        'content-type': 'application/json; charset=UTF-8'
      }
    })
      .then(function (response) {
        return response.json();
      })
      .then((data) => {
        localStorage.setItem('token', data.token);
        this.history.push(`/`, {});
      }).catch((err) => {
        console.log(err);
      });
  }
}

// angular/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Router } from '@angular/router';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {

  username: string;
  password: string;

  constructor(private httpclient: HttpClient, private router: Router) { }

  ngOnInit() {
  }

  login(){
    this.httpclient.post('http://localhost:4000/authenticate', { username: this.username , password: this.password }).subscribe((r: any) => {
      localStorage.setItem('token', r.token);
      this.router.navigate(['']);
    }, (error) => {
      console.log(`error`);
    });
  }
}

<form #f="ngForm" name="loginform" (ngSubmit)="login()">
  <div class="form-group col-sm-4">
    <label>Username</label>
    <input type="text" class="form-control" placeholder="Username" [(ngModel)]="username" name="username">
  </div>
  <div class="form-group col-sm-4">
    <label>Password</label>
    <input type="password" class="form-control" placeholder="Password" [(ngModel)]="password" name="password">
  </div>
  <div class="form-group col-sm-4">
    <button type="submit" class="btn btn-primary" (click)="login()">
      Login
    </button>
  </div>
</form>
